### ISSUE TITLE
Files should have permissions to execute

### ISSUE THREAD

**Issue by pavelkryukov** [petarpetrovt/setup-sde#13]
On Linux, I have the following error:

```
....SDE ERROR: Could not find file: /home/runner/work/putty-ci/putty-ci/.output/sde-temp-files/sde-external-8.59.0-2020-10-05-lin/intel64/sde-mix-mt.so
Is it possible you rearranged the kit files?
Please do not do that.
```

https://github.com/pavelkryukov/putty-ci/runs/1548872705#step:17:10

**Comment by petarpetrovt** [comment]
@pavelkryukov 
File `sde-mix-mt.so` seems to exists in CI test on row [80](https://github.com/petarpetrovt/setup-sde/runs/1555800242?check_suite_focus=true#step:7:80).

**Comment by pavelkryukov** [comment]
Interesting... may be it also needs a permission to execute?

**Comment by pavelkryukov** [comment]
Looks like running `chmod -R 755 $SDE_PATH` fixed that (see #12), but now I have the following error:

> libunwind-dynamic.so: file too short

**Comment by pavelkryukov** [comment]
Is it possible this file is a symbolic link?

**Comment by petarpetrovt** [comment]
Not sure it is possible. I will check it out on the weekends.

**Comment by pavelkryukov** [comment]
Hi, did you have a chance to check it?

**Comment by petarpetrovt** [comment]
@pavelkryukov  Should be fixed in latest version.

**Comment by pavelkryukov** [comment]
> Looks like running chmod -R 755 $SDE_PATH fixed that (see #12), but now I have the following error:
>
> ```libunwind-dynamic.so: file too short```
> 
> Is it possible this file is a symbolic link?

This is still an issue.
https://github.com/pavelkryukov/putty-ci/pull/12/checks?check_run_id=2046333462

**Comment by petarpetrovt** [comment]
@pavelkryukov yes that seems to be a symbolic link

**Comment by petarpetrovt** [comment]
@pavelkryukov  There was a problem with symlinks - i was extracting the SDE using `7zip` that doesn't support/create symlinks correctly, but i change it to use `tar` command only for `darwin` platforms (should include `linux` too probably).

I have released version `v1.1` that uses `tar` command for `linux` platforms too.

**Comment by pavelkryukov** [comment]
Works great. Thank you very much!
